name             'jetbrains_license_server'
maintainer       'Ryan Hass'
maintainer_email 'ryan_hass@rapid7.com'
license          'All rights reserved'
description      'Installs/Configures jetbrains_license_server'
long_description 'Installs/Configures jetbrains_license_server'
version          '0.1.0'

depends 'apt', '>= 2.6.0'
depends 'tomcat', '>= 0.16.2'
